apiVersion: database.example.org/v1alpha1
kind: PostgreSQLInstance
metadata:
  name: vivo-db
  namespace: vivo-4-0
spec:
  parameters:
    storageGB: 20
  compositionSelector:
    matchLabels:
      provider: gcp
  writeConnectionSecretToRef:
    name: vivo-db-conn