---
apiVersion: services.apps.tanzu.vmware.com/v1alpha1
kind: ResourceClaim
metadata:
  name: sample-api-accelerator-db-claim
  namespace: namespace_name
spec:
  ref:
    apiVersion: sql.tanzu.vmware.com/v1
    kind: Postgres
    name: sample-api-accelerator-postgres
    namespace: service-instances