apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: sample-api-accelerator
  namespace: namespace_name
  labels:
    apps.tanzu.vmware.com/workload-type: web
    app.kubernetes.io/part-of: sample-api-accelerator
spec:
  params:
    - name: annotations
      value:
        autoscaling.knative.dev/minScale: "1"
  source:
    git:
      url: git_repo_url
      ref:
        branch: git_repo_branch
  serviceClaims:
    - name: postgres
      ref:
        apiVersion: services.apps.tanzu.vmware.com/v1alpha1
        kind: ResourceClaim
        name: sample-api-accelerator-db-claim # name must match the service claim name