apiVersion: database.example.org/v1alpha1
kind: PostgreSQLInstance
metadata:
  name: vivo-db
  namespace: namespace_name
spec:
  parameters:
    storageGB: 20
  compositionSelector:
    matchLabels:
      provider: azure
  writeConnectionSecretToRef:
    name: vivo-db-conn